spring:
  profiles:
    active: local
    group:
      local: local_server, common, secret
      blue: blue_server, common, secret
      green: green_server, common, secret

---
# local_server ??
spring:
  config:
    activate:
      on-profile: local_server
server:
  port: 8080
client:
  address: http://localhost:3000

---
# blue_server ??
spring:
  config:
    activate:
      on-profile: blue_server
server:
  port: 8080
client:
  address: http://localhost:3000
---
# green_server ??
spring:
  config:
    activate:
      on-profile: green_server
server:
  port: 9090
client:
  address: http://localhost:3000
---
# server ?? ??
spring:
  config:
    activate:
      on-profile: common
mybatis:
  mapper-location:
    - mappers/*.xml